name: MacOS

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macOS-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run RaCoCo
        run: raku -Ilib bin/racoco --exec='prove6 t xt'
      - name: Discover Code Coverage
        run: |
          coverage=`head -1 .racoco/report.txt | sed 's/\..*//'`
          echo $coverage
          echo "COVERAGE=$coverage%" >> $GITHUB_ENV
      - name: Create Code Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_COCO_TOCKEN }}
          gistID: 3113bf626af5b82ec0917574e638fcf5
          filename: racoco-macos-coco.json
          namedLogo: Apple
          logoColor: 969da4
          label: Coverage
          labelColor: 343a41
          message: ${{ env.COVERAGE }}
          color: 5cb45a